%YAML 1.2
---
settings:
# default settings for the calculation
  massModel: "mass_point"      # type of train model used: "mass_point" or "homogeneous_strip"
  stepVariable: "distance"     # variable of the linear multistep method: "distance", "time" or "velocity"
  stepSize: 20                 # step size, unit depends on stepVariable - distance in meter, time in seconds and velocity in meter/second.
  approxLevel: 3               # value for approximation; used when rounding or interating
  outputDetail: "running_time" # single value "running_time", array of "points_of_interest",complete array "driving_course", or dict() "everything"
  outputFormat: "dataframe"    # output as "dataframe" or as "dict"
